In [226]:
import pandas as pd

In [227]:
data_frame=pd.read_csv("phone_reviews.csv")

In [228]:
data_frame.head()

,review,sentiment
0,Excellent value for money. Even though the bat...,positive
1,I am very happy with this phone; charging is f...,positive
2,Overall I regret buying this phone; the camera...,negative
3,Overall I regret buying this phone. Although t...,negative
4,This phone did not meet expectations. Even tho...,negative


In [229]:
data_frame["sentiment"].value_counts()

sentiment
positive    150
negative    150
Name: count, dtype: int64

In [230]:
data = data_frame["review"].tolist()
labels = data_frame["sentiment"].tolist()

In [231]:
labels[:5]

['positive', 'positive', 'negative', 'negative', 'negative']

In [232]:
data[:5]

['Excellent value for money. Even though the battery drains quickly, the camera captures sharp photos. It works very well for me.',
 'I am very happy with this phone; charging is fast and consistent, and the phone stays cool during use. It works very well for me.',
 'Overall I regret buying this phone; the camera quality is weak indoors, and call quality drops often. An unreliable phone overall.',
 'Overall I regret buying this phone. Although the phone stays cool during use, the battery drains quickly. Not worth the price.',
 'This phone did not meet expectations. Even though the phone stays cool during use, the software has frequent bugs. I would not buy it again.']

In [233]:
import nltk

nltk.download('punkt')


[nltk_data] Downloading package punkt to /home/sreekanth/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [234]:
from nltk.tokenize import sent_tokenize

from nltk.corpus import stopwords
from nltk.stem import PorterStemmer,WordNetLemmatizer
from nltk import pos_tag



In [235]:
def do_stop_words_removal(text):
    stop_words = set(stopwords.words('english'))
    removed_stop_words = [word for word in text.split() if word not in stop_words]

    return " ".join(removed_stop_words)

def do_sent_tokenize(para):
    sentences = sent_tokenize(para)
    return sentences

def do_word_tokenize(sentence):
    words = word_tokenize(sentence)
    return words

def do_stemming(words):
    ps = PorterStemmer()
    stemmed_words = []
    for word in words:
        stemmed_word = ps.stem(word)
        stemmed_words.append(stemmed_word)
    
    return " ".join(stemmed_words)
 
def do_lemmatization(words):
    lemmatizer = WordNetLemmatizer()
    lemmatized_words = []
    tagged_word = pos_tag(words)

    for tag_word in tagged_word:
        #pos tagging
       

        if tag_word[1].startswith('NN'):
            pos = 'n'
        elif tag_word[1].startswith('VB'):
            pos = 'v'
        elif tag_word[1].startswith('JJ'):
            pos = 'a'
        else:
            pos = 'n'   


        lemmatized_word = lemmatizer.lemmatize(tag_word[0], pos=pos)
        lemmatized_words.append(lemmatized_word)
    
    return " ".join(lemmatized_words)


    



In [236]:
up_to_lamitization = []

for para in data: 

    #Convert to LowerCase
    para = para.lower()

    #Remove Stop Words
    removed_stop_words_text = do_stop_words_removal(para)
 
    # print("After Stop Words Removal: ", removed_stop_words_text)

    #Sentence Tokenization
    tokenized_sentencses = do_sent_tokenize(removed_stop_words_text)
    # print("After Sentence Tokenization: ", tokenized_sentencses)


    multiple_sentences = []
    
    #Word Tokenization
    for index,sentence in enumerate(tokenized_sentencses):
        # print("processing...", sentence)

 
        tokenized_words = do_word_tokenize(sentence)
        # print("After Word Tokenization: ", tokenized_words)

        #Stemming
        stemmed_text = do_stemming(tokenized_words)
        # print("After Stemming: ", stemmed_text)

        #Lemmatization
        splitted_stemmed_text = stemmed_text.split()
        # print("Splitted Stemmed Text: ", splitted_stemmed_text)
        lemmatized_text = do_lemmatization(splitted_stemmed_text)
        # print("After Lemmatization: ", lemmatized_text)

        multiple_sentences.append(lemmatized_text)
       
        # print("Before Preprocessing: ", sentence)
        tokenized_sentencses[index] = " ".join(multiple_sentences)
        # print("After Preprocessing: ", tokenized_sentencses)
    up_to_lamitization.append(tokenized_sentencses[index])
    # print("After Preprocessing: ", tokenized_sentencses[index])
        

    
print("After Preprocessing: ", up_to_lamitization)


    
    


After Preprocessing:  ['excel valu money . even though batteri drain quickli , camera captur sharp photo . work well me .', 'happi phone ; charg fast consist , phone stay cool use . work well me .', 'overal regret buy phone ; camera qualiti weak indoor , call qualiti drop often . unreli phone overal .', 'overal regret buy phone . although phone stay cool use , batteri drain quickli . worth price .', 'phone meet expect . even though phone stay cool use , softwar frequent bug . would buy again .', 'phone meet expect ; phone overheat use , batteri drain quickli . unreli phone overal .', 'highli recommend devic . display look dull , display bright vibrant . happi purchas .', 'great experi far . although camera qualiti weak indoor , display bright vibrant . depend phone overal .', 'poor valu money . phone stay cool use , call qualiti drop often . worth price .', 'bad experi far ; call qualiti drop often , phone overheat use . worth price .', 'would recommend devic ; batteri drain quickli , 

In [237]:

from sklearn.preprocessing import OneHotEncoder
import numpy as np

In [238]:
one_hot_encoder = OneHotEncoder(sparse_output=False)

for entire_sentence in up_to_lamitization:
    re_shape = np.array(entire_sentence.split()).reshape(-1, 1)
    one_hot_encoded = one_hot_encoder.fit_transform(re_shape)
    print("Before One Hot Encoding: ", entire_sentence)
    print("One Hot Encoded: ", one_hot_encoded)


Before One Hot Encoding:  excel valu money . even though batteri drain quickli , camera captur sharp photo . work well me .
One Hot Encoded:  [[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0

In [239]:
from sklearn.feature_extraction.text import CountVectorizer

In [240]:
count_vectorizer = CountVectorizer()

vectorizer = count_vectorizer.fit_transform(up_to_lamitization)
print(vectorizer.toarray())
print(count_vectorizer.get_feature_names_out())


[[0 0 0 ... 1 0 0]
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [1 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 0]
 [1 0 1 ... 0 0 1]]
['again' 'although' 'app' 'bad' 'batteri' 'bright' 'bug' 'buy' 'call'
 'camera' 'captur' 'charg' 'clear' 'consist' 'cool' 'daili' 'day' 'depend'
 'devic' 'disappoint' 'display' 'drain' 'drop' 'dull' 'even' 'exceed'
 'excel' 'expect' 'experi' 'fantast' 'far' 'fast' 'feel' 'frequent'
 'frustrat' 'great' 'happi' 'highli' 'indoor' 'laggi' 'last' 'look' 'mani'
 'me' 'meet' 'money' 'often' 'overal' 'overheat' 'perform' 'phone' 'photo'
 'polish' 'poor' 'price' 'purchas' 'qualiti' 'quickli' 'recommend'
 'regret' 'satisfi' 'sharp' 'slow' 'smooth' 'softwar' 'stay' 'though'
 'unhappi' 'unreli' 'use' 'valu' 'vibrant' 'weak' 'well' 'work' 'worth'
 'would']


In [241]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [242]:
# count_vectorizer = TfidfVectorizer()

# vectorizer = count_vectorizer.fit_transform(up_to_lamitization)
# print(vectorizer.toarray())
# print(count_vectorizer.get_feature_names_out())


In [243]:
y=  data_frame["sentiment"].map({
    "positive":1,
    "negative":0
})
# print(Y)

In [244]:
X = vectorizer
Y = y

In [245]:
from sklearn.model_selection import train_test_split

In [246]:
X_train, X_test, Y_train, Y_test = train_test_split(
    X, Y, test_size=0.2, random_state=42
)

In [247]:
X_train.shape, Y_train.shape, X_test.shape, Y_test.shape

((240, 77), (240,), (60, 77), (60,))

In [248]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

model.fit(X_train, Y_train)

,"penalty penalty: {'l1', 'l2', 'elasticnet', None}, default='l2'Specify the norm of the penalty:- `None`: no penalty is added;- `'l2'`: add a L2 penalty term and it is the default choice;- `'l1'`: add a L1 penalty term;- `'elasticnet'`: both L1 and L2 penalty terms are added... warning:: Some penalties may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionadded:: 0.19 l1 penalty with SAGA solver (allowing 'multinomial' + L1).. deprecated:: 1.8 `penalty` was deprecated in version 1.8 and will be removed in 1.10. Use `l1_ratio` instead. `l1_ratio=0` for `penalty='l2'`, `l1_ratio=1` for `penalty='l1'` and `l1_ratio` set to any float between 0 and 1 for `'penalty='elasticnet'`.",'deprecated'
,"C C: float, default=1.0Inverse of regularization strength; must be a positive float.Like in support vector machines, smaller values specify strongerregularization. `C=np.inf` results in unpenalized logistic regression.For a visual example on the effect of tuning the `C` parameterwith an L1 penalty, see::ref:`sphx_glr_auto_examples_linear_model_plot_logistic_path.py`.",1.0
,"l1_ratio l1_ratio: float, default=0.0The Elastic-Net mixing parameter, with `0 <= l1_ratio <= 1`. Setting`l1_ratio=1` gives a pure L1-penalty, setting `l1_ratio=0` a pure L2-penalty.Any value between 0 and 1 gives an Elastic-Net penalty of the form`l1_ratio * L1 + (1 - l1_ratio) * L2`... warning:: Certain values of `l1_ratio`, i.e. some penalties, may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionchanged:: 1.8 Default value changed from None to 0.0... deprecated:: 1.8 `None` is deprecated and will be removed in version 1.10. Always use `l1_ratio` to specify the penalty type.",0.0
,"dual dual: bool, default=FalseDual (constrained) or primal (regularized, see also:ref:`this equation `) formulation. Dual formulationis only implemented for l2 penalty with liblinear solver. Prefer `dual=False`when n_samples > n_features.",False
,"tol tol: float, default=1e-4Tolerance for stopping criteria.",0.0001
,"fit_intercept fit_intercept: bool, default=TrueSpecifies if a constant (a.k.a. bias or intercept) should beadded to the decision function.",True
,"intercept_scaling intercept_scaling: float, default=1Useful only when the solver `liblinear` is usedand `self.fit_intercept` is set to `True`. In this case, `x` becomes`[x, self.intercept_scaling]`,i.e. a ""synthetic"" feature with constant value equal to`intercept_scaling` is appended to the instance vector.The intercept becomes``intercept_scaling * synthetic_feature_weight``... note:: The synthetic feature weight is subject to L1 or L2 regularization as all other features. To lessen the effect of regularization on synthetic feature weight (and therefore on the intercept) `intercept_scaling` has to be increased.",1
,"class_weight class_weight: dict or 'balanced', default=NoneWeights associated with classes in the form ``{class_label: weight}``.If not given, all classes are supposed to have weight one.The ""balanced"" mode uses the values of y to automatically adjustweights inversely proportional to class frequencies in the input dataas ``n_samples / (n_classes * np.bincount(y))``.Note that these weights will be multiplied with sample_weight (passedthrough the fit method) if sample_weight is specified... versionadded:: 0.17 *class_weight='balanced'*",None
,"random_state random_state: int, RandomState instance, default=NoneUsed when ``solver`` == 'sag', 'saga' or 'liblinear' to shuffle thedata. See :term:`Glossary ` for details.",None
,"solver solver: {'lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'}, default='lbfgs'Algorithm to use in the optimization problem. Default is 'lbfgs'.To choose a solver, you might want to consider the following aspects:- 'lbfgs' is a good default solver because it works reasonably well for a wide class of problems.- For :term:`mul

In [249]:
y_pred = model.predict(X_test)

In [250]:
print("Accuracy: ", model.score(X_test, Y_test))

Accuracy:  1.0
