In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("../phone_reviews.csv")
data.head()

,review
0,This phone has amazing camera quality and batt...
1,"Great phone overall, but the battery drains qu..."
2,Disappointed with the build quality. It feels ...


In [3]:
lowered_rows = [row["review"].lower() for _,row in data.iterrows()]
    
print(lowered_rows[:5])

['this phone has amazing camera quality and battery life!. the display is vibrant and the performance is top-notch. highly recommended for photography enthusiasts.', 'great phone overall, but the battery drains quickly. the screen is beautiful, and the apps run smoothly. would buy again.', 'disappointed with the build quality. it feels cheap, and the software has too many bugs. not worth the price.']


Tokenization


In [4]:
import nltk


In [5]:
from nltk.tokenize import sent_tokenize

sentences = []

for para in lowered_rows:
    sentences.append(sent_tokenize(para))

print(sentences[:5])

[['this phone has amazing camera quality and battery life!.', 'the display is vibrant and the performance is top-notch.', 'highly recommended for photography enthusiasts.'], ['great phone overall, but the battery drains quickly.', 'the screen is beautiful, and the apps run smoothly.', 'would buy again.'], ['disappointed with the build quality.', 'it feels cheap, and the software has too many bugs.', 'not worth the price.']]


In [6]:
# from nltk.tokenize import WordPunctTokenizer

# word_tokenizer = WordPunctTokenizer()
# tokenized_sentences = []
# for sentence in sentences:
#     for para in sentence:
#         tokenized_par = word_tokenizer.tokenize(para)
#         tokenized_sentences.append(" ".join(tokenized_par   ))

# print(tokenized_sentences[:5])

In [7]:
# Punctuation Removal
import string

punctuation_removed = []

for sentence_list in sentences:
    cleaned_sentences = []
    for sent in sentence_list:
        # Remove punctuation from each sentence
        cleaned_sent = ''.join(char for char in sent if char not in string.punctuation)
        cleaned_sentences.append(cleaned_sent)
    punctuation_removed.append(cleaned_sentences)

# Update sentences with cleaned version
sentences = punctuation_removed

print(sentences[:5])

[['this phone has amazing camera quality and battery life', 'the display is vibrant and the performance is topnotch', 'highly recommended for photography enthusiasts'], ['great phone overall but the battery drains quickly', 'the screen is beautiful and the apps run smoothly', 'would buy again'], ['disappointed with the build quality', 'it feels cheap and the software has too many bugs', 'not worth the price']]


In [8]:
# Stemming
from nltk.stem import RegexpStemmer
stemmer = RegexpStemmer("!$")

for index1, sentence in enumerate(sentences):
    for index2, para in enumerate(sentence):
        words = [stemmer.stem(word) for word in para.split()]
        joined_ = " ".join(words)
        print(joined_)
        sentences[index1][index2] = joined_



this phone has amazing camera quality and battery life
the display is vibrant and the performance is topnotch
highly recommended for photography enthusiasts
great phone overall but the battery drains quickly
the screen is beautiful and the apps run smoothly
would buy again
disappointed with the build quality
it feels cheap and the software has too many bugs
not worth the price


In [9]:
# Stemming
from nltk.stem import PorterStemmer
stemmer = PorterStemmer()

for index1, sentence in enumerate(sentences):
    for index2, para in enumerate(sentence):
        words = [stemmer.stem(word) for word in para.split()]
        joined_ = " ".join(words)
        print(joined_)
        sentences[index1][index2] = joined_



thi phone ha amaz camera qualiti and batteri life
the display is vibrant and the perform is topnotch
highli recommend for photographi enthusiast
great phone overal but the batteri drain quickli
the screen is beauti and the app run smoothli
would buy again
disappoint with the build qualiti
it feel cheap and the softwar ha too mani bug
not worth the price


In [10]:
# Stemming
from nltk.stem import SnowballStemmer
stemmer = SnowballStemmer("english")

for index1, sentence in enumerate(sentences):
    for index2, para in enumerate(sentence):
        words = [stemmer.stem(word) for word in para.split()]
        joined_ = " ".join(words)
        sentences[index1][index2] = joined_

print(sentences[:5])

[['thi phone ha amaz camera qualiti and batteri life', 'the display is vibrant and the perform is topnotch', 'high recommend for photographi enthusiast'], ['great phone over but the batteri drain quick', 'the screen is beauti and the app run smooth', 'would buy again'], ['disappoint with the build qualiti', 'it feel cheap and the softwar ha too mani bug', 'not worth the price']]


In [11]:
# Lamitization
nltk.download('wordnet')
nltk.download('omw-1.4')
nltk.download('averaged_perceptron_tagger')


[nltk_data] Downloading package wordnet to
[nltk_data]     /home/sreekanth/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     /home/sreekanth/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /home/sreekanth/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!


True

In [12]:
from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()

for index1, sentence in  enumerate(sentences):
    for index2, para in enumerate(sentence):
        words = nltk.word_tokenize(para)
        pos_tags = nltk.pos_tag(words)
        lamitized= []
        for word, tag in pos_tags:
            if tag.startswith('NN'):
                pos = 'n'
            elif tag.startswith('VB'):
                pos = 'v'
            elif tag.startswith('JJ'):
                pos = 'a'
            elif tag.startswith('RB'):
                pos= 'r'
            else:
                pos = 'n'
            lamitized.append(lemmatizer.lemmatize(word, pos))
        sentences[index1][index2] = " ".join(lamitized)
            
        # print(pos_tags)
print(sentences)

[['thi phone ha amaz camera qualiti and batteri life', 'the display be vibrant and the perform be topnotch', 'high recommend for photographi enthusiast'], ['great phone over but the batteri drain quick', 'the screen be beauti and the app run smooth', 'would buy again'], ['disappoint with the build qualiti', 'it feel cheap and the softwar ha too mani bug', 'not worth the price']]


In [13]:
# Stop Words 
from nltk.corpus import stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     /home/sreekanth/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [14]:
without_stop_words_se = []

for index, sentence in enumerate(sentences):
   for sent in sentence:
      without_stop_words = []
      for word in sent.split():
         if word not in set(stopwords.words("english")):
            without_stop_words.append(word)
      without_stop_words_sentence = " ".join(without_stop_words)
      without_stop_words_se.append(without_stop_words_sentence)
   
print(without_stop_words_se)

['thi phone ha amaz camera qualiti batteri life', 'display vibrant perform topnotch', 'high recommend photographi enthusiast', 'great phone batteri drain quick', 'screen beauti app run smooth', 'would buy', 'disappoint build qualiti', 'feel cheap softwar ha mani bug', 'worth price']


ONE HOT ENCODER

In [15]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

one_hot_encoder = OneHotEncoder(sparse_output= False)

one_array = []
for index, sentence in enumerate(without_stop_words_se):
    words = np.array(sentence.split()).reshape(-1, 1)

    encoded_sentence = one_hot_encoder.fit_transform(words)
    one_array.append(encoded_sentence)



print(one_array)

[array([[0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.]]), array([[1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]]), array([[0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.]]), array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1.]]), array([[0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1.]]), array([[0., 1.],
       [1., 0.]]), array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.]]), array([[0., 0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
    

In [16]:
from sklearn.feature_extraction.text import CountVectorizer

count_vectorizer = CountVectorizer()

X = count_vectorizer.fit_transform(without_stop_words_se)

print(X.toarray())
print(count_vectorizer.get_feature_names_out())

[[1 0 1 0 0 0 0 1 0 0 0 0 0 0 0 1 0 1 0 0 1 0 0 1 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 1 0 0 0 0 1 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0]]
['amaz' 'app' 'batteri' 'beauti' 'bug' 'build' 'buy' 'camera' 'cheap'
 'disappoint' 'display' 'drain' 'enthusiast' 'feel' 'great' 'ha' 'high'
 'life' 'mani' 'perform' 'phone' 'photographi' 'price' 'qualiti' 'quick'
 'recommend' 'run' 'screen' 'smooth' 'softwar' 'thi' 'topnotch' 'vibrant'
 'worth' 'would']


In [17]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_vectorizer = TfidfVectorizer()

X = tfidf_vectorizer.fit_transform(without_stop_words_se)

print(X.toarray())
print(tfidf_vectorizer.get_feature_names_out())

[[0.38198267 0.         0.32262864 0.         0.         0.
  0.         0.38198267 0.         0.         0.         0.
  0.         0.         0.         0.32262864 0.         0.38198267
  0.         0.         0.32262864 0.         0.         0.32262864
  0.         0.         0.         0.         0.         0.
  0.38198267 0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.5        0.
  0.         0.         0.         0.         0.         0.
  0.         0.5        0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.5        0.5        0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.5        0.         0.         0.         0.5        0.
  0.         0.         0.         0.5        0.         0.
  0.         0.5        0.  